"""maintenance

Revision ID: 0813cb9f5b50
Revises: 18a5c914c33e
Create Date: 2021-11-27 18:14:49.087421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0813cb9f5b50'
down_revision = '18a5c914c33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zug_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zug_id'], ['zug.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_employee_association',
    sa.Column('maintenance_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.email'], ),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_employee_association')
    op.drop_table('maintenance')
    # ### end Alembic commands ###
