"""waggon abstract

Revision ID: 096809f0bb1c
Revises: b07fef62bb58
Create Date: 2021-11-11 16:19:39.313617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096809f0bb1c'
down_revision = 'b07fef62bb58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personenwaggon',
    sa.Column('fahrgestellnummer', sa.String(length=64), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=True),
    sa.Column('sitzanzahl', sa.Integer(), nullable=True),
    sa.Column('maxGewicht', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fahrgestellnummer')
    )
    op.create_index(op.f('ix_personenwaggon_spurweite'), 'personenwaggon', ['spurweite'], unique=False)
    op.create_table('triebwagen',
    sa.Column('fahrgestellnummer', sa.String(length=64), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=True),
    sa.Column('zugkraft', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fahrgestellnummer')
    )
    op.create_index(op.f('ix_triebwagen_spurweite'), 'triebwagen', ['spurweite'], unique=False)
    op.drop_index('ix_waggon_spurweite', table_name='waggon')
    op.drop_table('waggon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waggon',
    sa.Column('fahrgestellnummer', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('spurweite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zugkraft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sitzanzahl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maxGewicht', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fahrgestellnummer', name='waggon_pkey')
    )
    op.create_index('ix_waggon_spurweite', 'waggon', ['spurweite'], unique=False)
    op.drop_index(op.f('ix_triebwagen_spurweite'), table_name='triebwagen')
    op.drop_table('triebwagen')
    op.drop_index(op.f('ix_personenwaggon_spurweite'), table_name='personenwaggon')
    op.drop_table('personenwaggon')
    # ### end Alembic commands ###
