"""removed is_available attribute of waggon

Revision ID: 10ace5279ef3
Revises: 0813cb9f5b50
Create Date: 2021-11-27 18:19:48.855678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ace5279ef3'
down_revision = '0813cb9f5b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personenwaggon', 'is_available')
    op.drop_column('triebwagen', 'is_available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triebwagen', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('personenwaggon', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
