"""trains

Revision ID: 1241b11b2e61
Revises: 
Create Date: 2021-11-20 20:01:54.324612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1241b11b2e61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('personenwaggon', sa.Column('zug_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'personenwaggon', 'zug', ['zug_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personenwaggon', type_='foreignkey')
    op.drop_column('personenwaggon', 'zug_id')
    op.drop_table('zug')
    # ### end Alembic commands ###
