"""test

Revision ID: 301a53f79ca6
Revises: 94e376c53f04
Create Date: 2021-11-20 21:13:33.206779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301a53f79ca6'
down_revision = '94e376c53f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('triebwagen_zug_id_fkey', 'triebwagen', type_='foreignkey')
    op.create_foreign_key(None, 'triebwagen', 'zug', ['zug_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('zug_triebwagen_fkey', 'zug', type_='foreignkey')
    op.create_foreign_key(None, 'zug', 'triebwagen', ['triebwagen'], ['fahrgestellnummer'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zug', type_='foreignkey')
    op.create_foreign_key('zug_triebwagen_fkey', 'zug', 'triebwagen', ['triebwagen'], ['fahrgestellnummer'], ondelete='SET NULL')
    op.drop_constraint(None, 'triebwagen', type_='foreignkey')
    op.create_foreign_key('triebwagen_zug_id_fkey', 'triebwagen', 'zug', ['zug_id'], ['id'])
    # ### end Alembic commands ###
