"""date data type

Revision ID: 36c845b75a53
Revises: 10ace5279ef3
Create Date: 2021-11-27 18:38:29.319627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c845b75a53'
down_revision = '10ace5279ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.add_column('maintenance', sa.Column('duration', sa.DECIMAL(), nullable=True))
    op.alter_column('maintenance', 'zug_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'zug_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('maintenance', 'duration')
    op.drop_column('maintenance', 'datetime')
    # ### end Alembic commands ###
