"""initial

Revision ID: 3f80c62b23ab
Revises: 
Create Date: 2021-11-16 10:07:49.038594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f80c62b23ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personenwaggon',
    sa.Column('fahrgestellnummer', sa.String(length=64), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=True),
    sa.Column('sitzanzahl', sa.Integer(), nullable=True),
    sa.Column('maxGewicht', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('fahrgestellnummer')
    )
    op.create_index(op.f('ix_personenwaggon_spurweite'), 'personenwaggon', ['spurweite'], unique=False)
    op.create_table('triebwagen',
    sa.Column('fahrgestellnummer', sa.String(length=64), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=True),
    sa.Column('zugkraft', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('fahrgestellnummer')
    )
    op.create_index(op.f('ix_triebwagen_spurweite'), 'triebwagen', ['spurweite'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_triebwagen_spurweite'), table_name='triebwagen')
    op.drop_table('triebwagen')
    op.drop_index(op.f('ix_personenwaggon_spurweite'), table_name='personenwaggon')
    op.drop_table('personenwaggon')
    # ### end Alembic commands ###
