"""description for maintenance

Revision ID: 8a3a3244c687
Revises: 36c845b75a53
Create Date: 2021-11-27 18:43:35.011999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3a3244c687'
down_revision = '36c845b75a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance', 'description')
    # ### end Alembic commands ###
