"""test

Revision ID: 94e376c53f04
Revises: b2eb7c70a9c7
Create Date: 2021-11-20 21:12:15.457178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e376c53f04'
down_revision = 'b2eb7c70a9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('personenwaggon_zug_id_fkey', 'personenwaggon', type_='foreignkey')
    op.create_foreign_key(None, 'personenwaggon', 'zug', ['zug_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('zug_triebwagen_fkey', 'zug', type_='foreignkey')
    op.create_foreign_key(None, 'zug', 'triebwagen', ['triebwagen'], ['fahrgestellnummer'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zug', type_='foreignkey')
    op.create_foreign_key('zug_triebwagen_fkey', 'zug', 'triebwagen', ['triebwagen'], ['fahrgestellnummer'])
    op.drop_constraint(None, 'personenwaggon', type_='foreignkey')
    op.create_foreign_key('personenwaggon_zug_id_fkey', 'personenwaggon', 'zug', ['zug_id'], ['id'])
    # ### end Alembic commands ###
