"""foreign key maintenance_emp_table on delete settings

Revision ID: af4fb79e65b4
Revises: 8a3a3244c687
Create Date: 2021-12-01 16:22:46.444070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4fb79e65b4'
down_revision = '8a3a3244c687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('maintenance_employee_association_maintenance_id_fkey', 'maintenance_employee_association', type_='foreignkey')
    op.drop_constraint('maintenance_employee_association_employee_id_fkey', 'maintenance_employee_association', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_employee_association', 'users', ['employee_id'], ['email'], ondelete='SET NULL')
    op.create_foreign_key(None, 'maintenance_employee_association', 'maintenance', ['maintenance_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_employee_association', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_employee_association', type_='foreignkey')
    op.create_foreign_key('maintenance_employee_association_employee_id_fkey', 'maintenance_employee_association', 'users', ['employee_id'], ['email'])
    op.create_foreign_key('maintenance_employee_association_maintenance_id_fkey', 'maintenance_employee_association', 'maintenance', ['maintenance_id'], ['id'])
    # ### end Alembic commands ###
