"""personenwaggon table

Revision ID: b07fef62bb58
Revises: b7b3451af82b
Create Date: 2021-11-11 16:14:27.410445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07fef62bb58'
down_revision = 'b7b3451af82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waggon', sa.Column('sitzanzahl', sa.Integer(), nullable=True))
    op.add_column('waggon', sa.Column('maxGewicht', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waggon', 'maxGewicht')
    op.drop_column('waggon', 'sitzanzahl')
    # ### end Alembic commands ###
