"""test

Revision ID: b2eb7c70a9c7
Revises: 1241b11b2e61
Create Date: 2021-11-20 20:17:54.811636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2eb7c70a9c7'
down_revision = '1241b11b2e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triebwagen', sa.Column('zug_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'triebwagen', 'zug', ['zug_id'], ['id'])
    op.add_column('zug', sa.Column('triebwagen', sa.String(), nullable=True))
    op.create_foreign_key(None, 'zug', 'triebwagen', ['triebwagen'], ['fahrgestellnummer'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zug', type_='foreignkey')
    op.drop_column('zug', 'triebwagen')
    op.drop_constraint(None, 'triebwagen', type_='foreignkey')
    op.drop_column('triebwagen', 'zug_id')
    # ### end Alembic commands ###
