"""triebwagen table

Revision ID: b7b3451af82b
Revises: 545e87780665
Create Date: 2021-11-11 16:12:51.438003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b3451af82b'
down_revision = '545e87780665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waggon',
    sa.Column('fahrgestellnummer', sa.String(length=64), nullable=False),
    sa.Column('spurweite', sa.Integer(), nullable=True),
    sa.Column('zugkraft', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fahrgestellnummer')
    )
    op.create_index(op.f('ix_waggon_spurweite'), 'waggon', ['spurweite'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waggon_spurweite'), table_name='waggon')
    op.drop_table('waggon')
    # ### end Alembic commands ###
